# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark"

# Site Setup
locale                   : "de-DE"
title                    : "SturmCamper"
title_separator          : "-"
subtitle                 : "Personal Site"
name                     : &name "Patrick Baracho Dittrich" # &name is a YAML anchor which can be *referenced later
description              : &description "Welcome to my personal website! I am Patrick. Here, you will find my portfolio, blog, and contact information."
url                      : https://sturmcamper.github.io/ # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "/" # the subpath of your site, e.g. "/blog"
repository               : "SturmCamper/SturmCamper.github.io"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : "/assets/images/icon.png" # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           :  # overrides the website title displayed in the masthead, use " " for no title

# Breadcrumbs
search: true



# Outputting
timezone: Europe/Berlin

# Includes
include:
  - _pages
  - assets/css/custom.css

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author Infos
author:
  name   : "Patrick Baracho Dittrich"
  avatar : "/assets/images/bio-photo.jpeg"
  bio    : "I am currently pursuing a master's in medical informatics with a strong passion for technology. My hobbies include home networking, and I have a keen interest in AI and software development. I love sports, particularly bouldering and volleyball. I use both Windows and Linux operating systems."
  location : "Baden-Würtemberg, Germany"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/SturmCamper"
    - label: "HS-Heilbronn"
      icon: "fab fa-fw fa-building"
      url: "https://www.hs-heilbronn.de/de/patrick.baracho-dittrich"
    - label: "Linked-In"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/pbarachodi/"

# Footer infos
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/SturmCamper"
    - label: "HS-Heilbronn"
      icon: "fab fa-fw fa-university"
      url: "https://www.hs-heilbronn.de/de/patrick.baracho-dittrich"
    - label: "Linked-In"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/pbarachodi/"

# Defaults
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

