# Site Setup
title: SturmCamper - Personal Site
email:
description: "Welcome to my personal website! I am Patrick. Here, you will find my portfolio, blog, and contact information."
github_username: SturmCamper
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Berlin
repository: "SturmCamper/SturmCamper.github.io"

# Includes
include:
  - _pages
  - assets/css/custom.css

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author Infos
author:
  name   : "Patrick Baracho Dittrich"
  avatar : "/assets/images/bio-photo.jpeg"
  bio    : "I am currently pursuing a master's in medical informatics with a strong passion for technology. My hobbies include home networking, and I have a keen interest in AI and software development. I love sports, particularly bouldering and volleyball. I use both Windows and Linux operating systems."
  location : "Baden-Würtemberg, Germany"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/SturmCamper"
    - label: "HS-Heilbronn"
      icon: "fab fa-fw fa-building"
      url: "https://www.hs-heilbronn.de/de/patrick.baracho-dittrich"
    - label: "Linked-In"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/pbarachodi/"

# Footer infos
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/SturmCamper"
    - label: "HS-Heilbronn"
      icon: "fab fa-fw fa-university"
      url: "https://www.hs-heilbronn.de/de/patrick.baracho-dittrich"
    - label: "Linked-In"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/pbarachodi/"

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
